name: x_clone
description: X clone done the right way
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.11
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.3
  get_it: ^7.7.0
  go_router: ^14.2.0
  image_picker: ^1.1.2
  injectable: ^2.4.2
  intl: ^0.19.0
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
